<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Game</RootNamespace>
    <AssemblyName>Game</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <None Update="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Libraries\**\*" CopyToOutputDirectory="PreserveNewest" TargetPath="%(Filename)%(Extension)" />
  </ItemGroup>
</Project>